# docker-compose.yml
version: '3'

services:
  mongo:
    image: mongo
    container_name: datastore
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
    - 27017:27017

  service:
    build: ../service
    links: 
    - mongo
    environment:
    - MONGO_URL=mongodb://datastore:27017
    ports:
    - "3001:3001"
    volumes:
    - ../service:/app

  app:
    build: ../ui
    links: 
    - service
    ports:
    - "3000:3000"
    volumes:
    - ../ui:/app



