# docker-compose.yml
version: '3'

services:
  mongo:
    image: mongo
    container_name: datastore
    volumes:
    - mongo:/data/db
    expose:
    - 27017:27017

  service:
    build: ../service
    links: 
    - mongo
    environment:
    - MONGO_URL=mongo://datastore:27017
    ports:
    - "3001:3001"
    volumes:
    - ../service:/app

  app:
    build: ../ui
    links: 
    - service
    ports:
    - "3000:3000"
    volumes:
    - ../ui:/app



